### ISSUE TITLE
Feedback for Lab Report 4

### ISSUE THREAD

**Issue by ShuhangXu** [nickjrjobe/cse15l-lab-reports#2]
Here is your feedback for Lab Report 4:
 
- [x] Provides link to their markdown-parse repository
- [x] Provides link to the markdown-parse repository they reviewed
 
Snippet 1
- [x] Shows the test(s) / expected output in MarkdownParseTest.java
- [x] Shows the output of running test(s) for their implementation
- [x] Shows the output of running for the implementation they reviewed
- [x] Answers the code change question about their program
 
Snippet 2
- [x] Shows the test(s) / expected output in MarkdownParseTest.java
- [x] Shows the output of running test(s) for their implementation
- [x] Shows the output of running for the implementation they reviewed
- [x] Answers the code change question about their program
 
Snippet 3
- [x] Shows the test(s) / expected output in MarkdownParseTest.java
- [x] Shows the output of running test(s) for their implementation
- [x] Shows the output of running for the implementation they reviewed
- [x] Answers the code change question about their program
 
Additional comments from your grader:
 Nice work. Please include the screenshot of output of running test(s) for other group's implementation
Feel free to comment below any questions about the rubric/feedback
 
--------
 
If you don't have all the checkmarks above, fix the issues described, and then submit a [regrade request on Gradescope](https://help.gradescope.com/article/8hchz9h8wh-student-regrade-request). Use this template for your regrade request:
 
Link to this issue
Link to your published lab report page

**Comment by nickjrjobe** [comment]
I'm not sure I understand what you mean by this, because I think I already did so. If not, could you please elaborate on what exactly I should fix.

**Comment by ShuhangXu** [comment]
Hi, updated. I need the screenshot of your implementation. For now, the picture of your implementation cannot get loaded.
![image](https://user-images.githubusercontent.com/67384845/169924112-6ea527eb-331b-4760-96d3-75cf83540c03.png)

**Comment by nickjrjobe** [comment]
I'm not sure why this is happening but I just repasted the path. Could you please check if it is working on your end now? Thanks in advance.

**Comment by ShuhangXu** [comment]
It works! Thank you and I will get your points back
